services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: vocabulate-php
    # depends_on:
    #   - nginx
    #   - db
    #   - mailhog
    restart: always
    working_dir: /var/www
    volumes:
      - ../app:/var/www

  nginx:
    image: nginx:1.29-alpine
    container_name: vocabulate-webserver
    restart: always
    ports:
      - "9095:80"
    volumes:
      - ../app:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: vocabulate-db
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    container_name: vocabulate-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
