FROM php:8.4-fpm-alpine
RUN find /var/www

RUN apk add --no-cache \
    curl \
    git \
    unzip \
    zip \
    libzip-dev \
    autoconf \
    build-base \
    gcc \
    linux-headers

RUN pecl install xdebug \
 && docker-php-ext-enable xdebug

RUN docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

COPY ./app .

RUN composer install --no-interaction --prefer-dist --optimize-autoloader
